package dao;
// Generated 2019-10-09 13:52:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private String idcategorie;
     private String nom;
     private String description;
     private Set medicaments = new HashSet(0);

    public Categorie() {
    }

	
    public Categorie(String idcategorie, String nom, String description) {
        this.idcategorie = idcategorie;
        this.nom = nom;
        this.description = description;
    }
    public Categorie(String idcategorie, String nom, String description, Set medicaments) {
       this.idcategorie = idcategorie;
       this.nom = nom;
       this.description = description;
       this.medicaments = medicaments;
    }
   
    public String getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(String idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMedicaments() {
        return this.medicaments;
    }
    
    public void setMedicaments(Set medicaments) {
        this.medicaments = medicaments;
    }




}


