package dao;
// Generated 2019-10-09 13:52:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicament generated by hbm2java
 */
public class Medicament  implements java.io.Serializable {


     private String idmed;
     private Categorie categorie;
     private String nommed;
     private BigDecimal prix;
     private Set ordonnancemedicamentses = new HashSet(0);

    public Medicament() {
    }

	
    public Medicament(String idmed, String nommed, BigDecimal prix) {
        this.idmed = idmed;
        this.nommed = nommed;
        this.prix = prix;
    }
    public Medicament(String idmed, Categorie categorie, String nommed, BigDecimal prix, Set ordonnancemedicamentses) {
       this.idmed = idmed;
       this.categorie = categorie;
       this.nommed = nommed;
       this.prix = prix;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
   
    public String getIdmed() {
        return this.idmed;
    }
    
    public void setIdmed(String idmed) {
        this.idmed = idmed;
    }
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }
    public String getNommed() {
        return this.nommed;
    }
    
    public void setNommed(String nommed) {
        this.nommed = nommed;
    }
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }
    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    
    public void setOrdonnancemedicamentses(Set ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }




}


