package dao;
// Generated 2019-10-09 13:52:18 by Hibernate Tools 4.3.1



/**
 * Ordonnancechirurgie generated by hbm2java
 */
public class Ordonnancechirurgie  implements java.io.Serializable {


     private OrdonnancechirurgieId id;
     private Ordonnance ordonnance;
     private String nomchirurgie;

    public Ordonnancechirurgie() {
    }

    public Ordonnancechirurgie(OrdonnancechirurgieId id, Ordonnance ordonnance, String nomchirurgie) {
       this.id = id;
       this.ordonnance = ordonnance;
       this.nomchirurgie = nomchirurgie;
    }
   
    public OrdonnancechirurgieId getId() {
        return this.id;
    }
    
    public void setId(OrdonnancechirurgieId id) {
        this.id = id;
    }
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }
    public String getNomchirurgie() {
        return this.nomchirurgie;
    }
    
    public void setNomchirurgie(String nomchirurgie) {
        this.nomchirurgie = nomchirurgie;
    }




}


