package dao;
// Generated 2019-10-09 13:52:18 by Hibernate Tools 4.3.1



/**
 * OrdonnancechirurgieId generated by hbm2java
 */
public class OrdonnancechirurgieId  implements java.io.Serializable {


     private String numord;
     private short rang;

    public OrdonnancechirurgieId() {
    }

    public OrdonnancechirurgieId(String numord, short rang) {
       this.numord = numord;
       this.rang = rang;
    }
   
    public String getNumord() {
        return this.numord;
    }
    
    public void setNumord(String numord) {
        this.numord = numord;
    }
    public short getRang() {
        return this.rang;
    }
    
    public void setRang(short rang) {
        this.rang = rang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancechirurgieId) ) return false;
		 OrdonnancechirurgieId castOther = ( OrdonnancechirurgieId ) other; 
         
		 return ( (this.getNumord()==castOther.getNumord()) || ( this.getNumord()!=null && castOther.getNumord()!=null && this.getNumord().equals(castOther.getNumord()) ) )
 && (this.getRang()==castOther.getRang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumord() == null ? 0 : this.getNumord().hashCode() );
         result = 37 * result + this.getRang();
         return result;
   }   


}


